name: build frp docker image
on:
  push:
    branches: [ frp ]

env:
  IMAGE_NAME: frp
  IMAGE_VERSION: 0.46.0
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Download and Extract Frp
        id: download
        run: |
          curl -L https://github.com/fatedier/frp/releases/download/v${{ env.IMAGE_VERSION }}/frp_${{ env.IMAGE_VERSION }}_linux_amd64.tar.gz | tar -zx
          mkdir bin
          mv frp_${{ env.IMAGE_VERSION }}_linux_amd64/frps bin/
          mv frp_${{ env.IMAGE_VERSION }}_linux_amd64/frpc bin/

      - name: Build and push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
