name: build php:7.4-apache docker image

on:
  push:
    branches: [ "7.4-apache" ]

env:
  IMAGE_NAME: php
  IMAGE_VERSION: 7.4-apache
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.ALIYUN_REGISTRY }}/${{ secret.ALIYUN_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}