name: build frp docker image

on:
  push:
    branches: [ frp ]

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: zapic-default/frp
  FRP_VERSION: 0.46.0
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
		
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Download and Extract Frp
        id: download
        run: |
          curl -L https://github.com/fatedier/frp/releases/download/v${{ env.FRP_VERSION }}/frp_${{ env.FRP_VERSION }}_linux_amd64.tar.gz | tar -zx
          mkdir bin
          mv frp_${{ env.FRP_VERSION }}_linux_amd64/frps bin/
          mv frp_${{ env.FRP_VERSION }}_linux_amd64/frpc bin/
		  
      - name: Build and push ${{ env.IMAGE_NAME }}:${{ env.FRP_VERSION }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FRP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
